/*
 * Copyright 2017 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.nbgames.gunu;

import javax.swing.SwingUtilities;
import org.nbgames.core.api.options.NbgOptionsPanel;
import se.trixon.almond.util.Dict;

final class OptionsPanel extends NbgOptionsPanel {

    private final Options mOptions = Options.getInstance();

    public OptionsPanel() {
        initComponents();
        load();
    }

    @Override
    public void load() {
        SwingUtilities.invokeLater(() -> {
            bgColorComboBox.setSelectedColor(mOptions.getColorBackground());
        });
    }

    @Override
    public void save() {
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgLabel = new javax.swing.JLabel();
        bgColorComboBox = new org.openide.awt.ColorComboBox();
        fgLabel = new javax.swing.JLabel();
        fgColorComboBox = new org.openide.awt.ColorComboBox();

        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(bgLabel, Dict.BACKGROUND.toString());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(bgLabel, gridBagConstraints);

        bgColorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgColorComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(bgColorComboBox, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(fgLabel, Dict.FOREGROUND.toString());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        add(fgLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(fgColorComboBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void bgColorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgColorComboBoxActionPerformed
        mOptions.setColorBackground(bgColorComboBox.getSelectedColor());
    }//GEN-LAST:event_bgColorComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.awt.ColorComboBox bgColorComboBox;
    private javax.swing.JLabel bgLabel;
    private org.openide.awt.ColorComboBox fgColorComboBox;
    private javax.swing.JLabel fgLabel;
    // End of variables declaration//GEN-END:variables
}
